apiVersion: apps/v1
kind: Deployment

metadata:
  name: revueon-deployment
  namespace: revueon-ns
  labels:
    apps: revueon

spec:
  replicas: 1
  selector:
    matchLabels:
      app: revueon
  template:
    metadata:
      labels:
        app: revueon
    spec:
      containers:
        - name: revueon
          image: gopal161/revueon-landing-page:latest
          ports:
            - containerPort: 80
